FROM alpine:latest

RUN apk update && \
    apk add --no-cache nginx git perl && \
    cd /tmp && \
    git clone https://github.com/jasonm23/cowsay.git && \
    cd cowsay && \
    ./install.sh /usr/local && \
    cd / && \
    rm -rf /var/cache/apk/* /var/tmp/* /tmp/* && \
    apk del git

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/html

RUN cowsay 'Hello World' > /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
